// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: idl/MapleJuice.proto

package idl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exe         string `protobuf:"bytes,1,opt,name=exe,proto3" json:"exe,omitempty"`
	NumMaples   int32  `protobuf:"varint,2,opt,name=numMaples,proto3" json:"numMaples,omitempty"`
	Prefix      string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	SrcDir1     string `protobuf:"bytes,4,opt,name=srcDir1,proto3" json:"srcDir1,omitempty"`
	SrcDir2     string `protobuf:"bytes,5,opt,name=srcDir2,proto3" json:"srcDir2,omitempty"`
	Regex       string `protobuf:"bytes,6,opt,name=regex,proto3" json:"regex,omitempty"`
	JoinColumn1 int32  `protobuf:"varint,7,opt,name=joinColumn1,proto3" json:"joinColumn1,omitempty"`
	JoinColumn2 int32  `protobuf:"varint,8,opt,name=joinColumn2,proto3" json:"joinColumn2,omitempty"`
}

func (x *MapleRequest) Reset() {
	*x = MapleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_MapleJuice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapleRequest) ProtoMessage() {}

func (x *MapleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_MapleJuice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapleRequest.ProtoReflect.Descriptor instead.
func (*MapleRequest) Descriptor() ([]byte, []int) {
	return file_idl_MapleJuice_proto_rawDescGZIP(), []int{0}
}

func (x *MapleRequest) GetExe() string {
	if x != nil {
		return x.Exe
	}
	return ""
}

func (x *MapleRequest) GetNumMaples() int32 {
	if x != nil {
		return x.NumMaples
	}
	return 0
}

func (x *MapleRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *MapleRequest) GetSrcDir1() string {
	if x != nil {
		return x.SrcDir1
	}
	return ""
}

func (x *MapleRequest) GetSrcDir2() string {
	if x != nil {
		return x.SrcDir2
	}
	return ""
}

func (x *MapleRequest) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

func (x *MapleRequest) GetJoinColumn1() int32 {
	if x != nil {
		return x.JoinColumn1
	}
	return 0
}

func (x *MapleRequest) GetJoinColumn2() int32 {
	if x != nil {
		return x.JoinColumn2
	}
	return 0
}

type MapleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *MapleResponse) Reset() {
	*x = MapleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_MapleJuice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapleResponse) ProtoMessage() {}

func (x *MapleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_MapleJuice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapleResponse.ProtoReflect.Descriptor instead.
func (*MapleResponse) Descriptor() ([]byte, []int) {
	return file_idl_MapleJuice_proto_rawDescGZIP(), []int{1}
}

func (x *MapleResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type JuiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exe         string `protobuf:"bytes,1,opt,name=exe,proto3" json:"exe,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Prefix      string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	OutDir      string `protobuf:"bytes,4,opt,name=outDir,proto3" json:"outDir,omitempty"`
	DeleteInput string `protobuf:"bytes,5,opt,name=deleteInput,proto3" json:"deleteInput,omitempty"`
}

func (x *JuiceRequest) Reset() {
	*x = JuiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_MapleJuice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JuiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JuiceRequest) ProtoMessage() {}

func (x *JuiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_MapleJuice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JuiceRequest.ProtoReflect.Descriptor instead.
func (*JuiceRequest) Descriptor() ([]byte, []int) {
	return file_idl_MapleJuice_proto_rawDescGZIP(), []int{2}
}

func (x *JuiceRequest) GetExe() string {
	if x != nil {
		return x.Exe
	}
	return ""
}

func (x *JuiceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *JuiceRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *JuiceRequest) GetOutDir() string {
	if x != nil {
		return x.OutDir
	}
	return ""
}

func (x *JuiceRequest) GetDeleteInput() string {
	if x != nil {
		return x.DeleteInput
	}
	return ""
}

type JuiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *JuiceResponse) Reset() {
	*x = JuiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_MapleJuice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JuiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JuiceResponse) ProtoMessage() {}

func (x *JuiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_MapleJuice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JuiceResponse.ProtoReflect.Descriptor instead.
func (*JuiceResponse) Descriptor() ([]byte, []int) {
	return file_idl_MapleJuice_proto_rawDescGZIP(), []int{3}
}

func (x *JuiceResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_idl_MapleJuice_proto protoreflect.FileDescriptor

var file_idl_MapleJuice_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x64, 0x6c, 0x2f, 0x4d, 0x61, 0x70, 0x6c, 0x65, 0x4a, 0x75, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x70, 0x6c, 0x65, 0x6a, 0x75, 0x69,
	0x63, 0x65, 0x22, 0xe4, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x78, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x4d, 0x61, 0x70, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x4d, 0x61, 0x70,
	0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x72, 0x63, 0x44, 0x69, 0x72, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x72,
	0x63, 0x44, 0x69, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x44, 0x69, 0x72, 0x32,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x72, 0x63, 0x44, 0x69, 0x72, 0x32, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x65, 0x67, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x31, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6a, 0x6f,
	0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x32, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x61, 0x70,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x0c, 0x4a, 0x75, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x78, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x44, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x4a, 0x75, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x32, 0x9d, 0x01, 0x0a, 0x11, 0x4d, 0x61, 0x70, 0x6c, 0x65, 0x4a, 0x75, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x70, 0x6c, 0x65,
	0x6a, 0x75, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x70, 0x6c, 0x65, 0x6a, 0x75, 0x69, 0x63, 0x65, 0x2e,
	0x4d, 0x61, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4a, 0x75, 0x69, 0x63, 0x65, 0x12, 0x18, 0x2e,
	0x6d, 0x61, 0x70, 0x6c, 0x65, 0x6a, 0x75, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x70, 0x6c, 0x65, 0x6a,
	0x75, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x64, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_idl_MapleJuice_proto_rawDescOnce sync.Once
	file_idl_MapleJuice_proto_rawDescData = file_idl_MapleJuice_proto_rawDesc
)

func file_idl_MapleJuice_proto_rawDescGZIP() []byte {
	file_idl_MapleJuice_proto_rawDescOnce.Do(func() {
		file_idl_MapleJuice_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_MapleJuice_proto_rawDescData)
	})
	return file_idl_MapleJuice_proto_rawDescData
}

var file_idl_MapleJuice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_MapleJuice_proto_goTypes = []interface{}{
	(*MapleRequest)(nil),  // 0: maplejuice.MapleRequest
	(*MapleResponse)(nil), // 1: maplejuice.MapleResponse
	(*JuiceRequest)(nil),  // 2: maplejuice.JuiceRequest
	(*JuiceResponse)(nil), // 3: maplejuice.JuiceResponse
}
var file_idl_MapleJuice_proto_depIdxs = []int32{
	0, // 0: maplejuice.MapleJuiceService.ExecuteMaple:input_type -> maplejuice.MapleRequest
	2, // 1: maplejuice.MapleJuiceService.ExecuteJuice:input_type -> maplejuice.JuiceRequest
	1, // 2: maplejuice.MapleJuiceService.ExecuteMaple:output_type -> maplejuice.MapleResponse
	3, // 3: maplejuice.MapleJuiceService.ExecuteJuice:output_type -> maplejuice.JuiceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_MapleJuice_proto_init() }
func file_idl_MapleJuice_proto_init() {
	if File_idl_MapleJuice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_MapleJuice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_MapleJuice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_MapleJuice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JuiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_MapleJuice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JuiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_MapleJuice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_MapleJuice_proto_goTypes,
		DependencyIndexes: file_idl_MapleJuice_proto_depIdxs,
		MessageInfos:      file_idl_MapleJuice_proto_msgTypes,
	}.Build()
	File_idl_MapleJuice_proto = out.File
	file_idl_MapleJuice_proto_rawDesc = nil
	file_idl_MapleJuice_proto_goTypes = nil
	file_idl_MapleJuice_proto_depIdxs = nil
}
